### ISSUE TITLE
Lab testing with async functions ;)

### ISSUE THREAD

**Issue by kristianmandrup** [senecajs/seneca#150]
I'm trying to port seneca for use with ES7 async constructs, to avoid callback hell. 
However it was not clear to me, how to run the tests with ES7/Babel turned on.
Here is my solution if anyone else feels like going down that path... (or help me on my async port)

`npm test` runs the `test` script as configured in `package.json`:

`"test": "./node_modules/.bin/lab -v -P test"`

So clearly, for the tests to work, we must use lab as the runner with babel configured to use ES7 async functions...

if we look in `node_modules` we can see that `.bin/lab` is a simple node executable

```sh
#!/usr/bin/env node

require('../lib/cli').run();
```

We can create our own tes runner to wrap lab, such as: `lab-cli.js`

```js
require('lab/lib/cli').run();
```

`node lab-cli.js -v -P test --require ./babel-async`

where `babel-async.js` contains or babel config that enables ES7 async functions:

```js
require('babel/register')({
  'optional': [ 'es7.asyncFunctions' ]
});
```

**Comment by AdrianRossouw** [comment]
Many of the async lab tests are incorrect at the moment.

for example : 
https://github.com/rjrodger/seneca/blob/master/test/delegation.test.js#L24-L44

```
  it('happy', function(done) {
    var si  = seneca_module(testopts)
    si.add({c:'C'},function(args,cb){
      cb(null,args)
    })
    var sid = si.delegate({a$:'A',b:'B'})


    assert.ok(gex("Seneca/0.*.*/*").on(si.toString()))
    assert.ok(gex("Seneca/0.*.*/*/{b:B}").on(sid.toString()))


    si.act({c:'C'},function(err,out){
      assert.ok(gex("{c=C,*}").on( common.owndesc(out,1,true)))
    })

    sid.act({c:'C'},function(err,out){
      assert.ok(gex("{c=C,a$=A,b=B,*}").on( common.owndesc(out,1,true)))
    })
    done()
  })
```

None of the asserts are ever triggered, which means it always passes even if it could be completely broken.

While I am not suggesting we rewrite the tests (again) using [tape](https://github.com/substack/tape), this is why tape has the [t.plan(n)](https://github.com/substack/tape#example) method.

I really think you are going to need to fix the tests first before trying to port them to babel.

Another thing to note is that seneca is incompatible with fat arrow functions, because it relies on being able to specify the `this` context on callbacks registered with it.

**Comment by kristianmandrup** [comment]
Thanks :) Yeah, I see... might need a rewrite of the test suite using mocha/chai with async :P
Regarding arrow functions. I already refactored seneca to not use callbacks but instead use async functions with await instead of callbacks. Then I just need to ditch the `this` for context I guess... somehow. Thanks again :)

**Comment by AdrianRossouw** [comment]
the tests were already written in mocha before they were rewritten into lab. I'm not exactly sure why this decision was made, because as far as I can see lab is kind of hapi-oriented, but maybe @rjrodger can enlighten us.

I personally feel that tape is a more appropriate tool because it's easier to parallelise tests written with it, and a couple of other reasons. But it's really just bike shedding, because having tests in lab is a far far better situation than not having any tests in tape.

As far as removing the context, I'm not sure that is going to be possible without forking seneca into something new. This is the basic pattern that doesn't work :

```javascript
module.exports = (opts) => {
  // this will always point to the window object
  var seneca = this; 

  // this.prior will never point to the right thing, only the defining scope  
  seneca.add('role:srv,cmd:cmd', (args, done) =>  { this.prior(args, done) } );
}
```

You can see what [babel does to it for instance](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=true&code=%0A%0Amodule.exports%20%3D%20(opts)%20%3D%3E%20%7B%0A%20%20%2F%2F%20this%20will%20always%20point%20to%20the%20window%20object%0A%20%20var%20seneca%20%3D%20this%3B%20%0A%0A%20%20%2F%2F%20this%20will%20never%20point%20to%20the%20right%20thing%2C%20only%20the%20defining%20scope%20%20%0A%20%20seneca.add('role%3Asrv%2Ccmd%3Acmd'%2C%20(args%2C%20done)%20%3D%3E%20%20%7B%20this.prior(args%2C%20done)%20%7D%20)%3B%0A%7D%0A).

Changing this means that none of the seneca-* modules will work without breaking their api.

It's probably a better idea for you to start with the [core of the new seneca](https://github.com/senecajs/zeno) that is being developed, and build up from there, than it is to try and make the changes you are attempting to the existing seneca codebase.

**Comment by AdrianRossouw** [comment]
It just occurred to me it might be possible to provide some compatibility with fat arrow functions if you use [Function.length](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) (which in itself is a bit dodgy, and has some interesting edge cases with the newly introduced rest parameters.).

You could make it do :

```javascript
module.exports = (seneca, opts) =>
  seneca.add('role:srv,cmd:cmd', (si, args, done) => si.prior(args, done) );
```

**Comment by kristianmandrup** [comment]
`Function.length?` huh? where? how? well thanks :) Been going pretty far down the `async` road already!
Thanks for the pointer to the new Seneca. Well basically, I felt the current impl kinda "sucked" coz pretty much everything was bundled up in one huge +4000 loc file. Not exactly the Node way IMO.
So much up for my current refactoring/redesign was to modularize it into logical small chunks. 
Well, let's see where it goes... any assistance or advice greatly appreciated! Cheers!

**Comment by AdrianRossouw** [comment]
You can use the length to tell how many arguments were defined in the function.

```javascript
(function oldForm(done) {}).length; // prints 1
(function newForm(seneca, done) {}).length; // prints 2
```

Anyway, this is all very far from the original question you had. can we close this issue?

**Comment by geek** [comment]
I can cleanup the tests.  I think the decision to go with lab is centered around me being the maintainer of lab... meaning I can help support our needs in seneca testing.

With lab we can run tests in parallel if we need.

**Comment by AdrianRossouw** [comment]
the async tests need something like the following, but the side effect is that any assert that fails doesn't error out with the right error, it just times out because the assert causes the callback to never be hit. This is what tape's `t.plan(n)` handles.

```javascript
  it('happy', function(done) {
    var complete = _.after(2, done)
    
    var si  = seneca_module(testopts)
    si.add({c:'C'},function(args,cb){
      cb(null,args)
    })
    var sid = si.delegate({a$:'A',b:'B'})


    assert.ok(gex("Seneca/0.*.*/*").on(si.toString()))
    assert.ok(gex("Seneca/0.*.*/*/{b:B}").on(sid.toString()))


    si.act({c:'C'},function(err,out){
      assert.ok(gex("{c=C,*}").on( common.owndesc(out,1,true)))
      complete()
    })

    sid.act({c:'C'},function(err,out){
      assert.ok(gex("{c=C,a$=A,b=B,*}").on( common.owndesc(out,1,true)))
      complete()
    })
  })
```

**Comment by geek** [comment]
These are now fixed, closing this issue.
