### ISSUE TITLE
pdf file as repsonse

### ISSUE THREAD

**Issue by neoms21** [senecajs/seneca#278]
Hi,

I need to send pdf file as response when the action has completed but I can't seem to figure out where to set content-type etc and where to put the pdf filestream.

Please help.

**Comment by mcdonnelldean** [comment]
@neoms21 What transport are you using? Just the built in ones? Generally we don't expose this because the Transport may not be HTTP but then I can see the reasoning.

@geek @rjrodger We should probably look at what to do in this instance. This relates to having streams as responses too which came up before.

**Comment by neoms21** [comment]
@mcdonnelldean We're using http transport using seneca-web. I couldn't figure out anything so for now have gone with pure express api call to achieve the same

**Comment by mcollina** [comment]
I would discourage anybody trying to send possibly big files using request/response patterns. Even we might make it work, the performance will be ugly.
Given that generating a PDF is a CPU intensive operation, and they are usually stored somewhere after being generated, it is way better to have it done inside a queue, stored somewhere (S3?) and then streamed down to the client from there (or worst-case streamed down from express).

**Comment by mcollina** [comment]
Currently Seneca does not support streams inside the messages, we have been talking about it for a while.

**Comment by mcdonnelldean** [comment]
@neoms21 I had a chat with @rjrodger about this and he pretty much said what @mcollina said line for line. How he does this usually is sends a reference to an S3 file in the message, something external to seneca handles the actual upload / download. Otherwise the volume of data and operation intensity will kill pref.

**Comment by neoms21** [comment]
cheers @mcdonnelldean I get it. That's what I ended up doing. Cheers for all your time.

**Comment by mcdonnelldean** [comment]
Awesome! We will look at streaming at some point but it would be with a warning that it's more for interfacing with streams than sending heavy data.

Either way, delighted you got it sorted. Any more q's just make an issue :D
