### ISSUE TITLE
Change .publish() to a more fitting name

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca#300]
Seneca.publish for fire and forget is misleading in my opinion, generally publish is used in conjunction with subscribe.

It also clashes with decorating seneca with actual pubsub as in `seneca-pubsub`

Can we come up with a name that works better for what is actually being done. Maybe,

- emit
- dispatch
- fire

**Comment by thekemkid** [comment]
+1 for fire.

**Comment by geek** [comment]
@mcdonnelldean we have `sub`, maybe it should be renamed to `pub`... Its not a fire and forget, since we do care if an error occurs in the publish process.  The thing I am going to change for now is to swallow the response, if there is one.  It will be easier to add this back later than it will be to remove later.

**Comment by mcollina** [comment]
The problem is that seneca is not a publish-subscribe system. What `publish` does it so send the message to all the matching handlers, and collect (correct me if I am wrong) the responses. Also, it does not work across seneca instances (over transports), so it has limited utility.

I would possibly scrap the feature in v2, and maybe replace it with something that is true pubsub. I would suggest we follow the same approach used in seneca-queue.

**Comment by geek** [comment]
In this case, since the feature hasn't shipped... I am going to pull it out for v1.  We can always decorate seneca from a plugin with a `fire` or other function to do what this function did.  However, if we keep it as-is then it will be harder to remove or change down the line. And since it already is causing issues before it even ships, might as well remove :)

@thekemkid I can help move this to a plugin.
