### ISSUE TITLE
Multi-tenanted using Seneca Mongo Data Store

### ISSUE THREAD

**Issue by nicholaschantcs** [senecajs/seneca#354]
Hi,

I am trying to achieve multi-tenant using this example from [https://github.com/edappy/seneca-multi-mongo-example](https://github.com/edappy/seneca-multi-mongo-example). I found out that it works fine in this example as it is using an older version of Seneca which is 0.6.5 but when I try to run it with the latest version of Seneca 1.2.0 , it will ignore the first seneca.use and proceed with the last seneca.use resulting in only saving to the test2 database.

```javascript
seneca.use('mongo-store$test', _.assign(dbOptions, {name: 'test', map:{'test/-/-':'*'}}));
seneca.use('mongo-store$test2', _.assign(dbOptions, {name: 'test2', map:{'test2/-/-':'*'}}));
```

I was wondering if there are any other alternatives towards this or any other solutions to implement multi-tenancy using Seneca?

**Comment by geek** [comment]
@nicholaschantcs good catch.  One alternative, to get this to work, is to change the store name for each case.  You could fork the seneca-mongo-store and make it so that the store name is set to the options.name passed in if there is one.  Right now its https://github.com/rjrodger/seneca-mongo-store/blob/master/mongo-store.js#L9 and could be overridden on https://github.com/rjrodger/seneca-mongo-store/blob/master/mongo-store.js#L90 

```js
name = opts.name || name
```

**Comment by mcdonnelldean** [comment]
@geek @nicholaschantcs We have a few friends who have done this, give me few days to root something out for you

**Comment by nicholaschantcs** [comment]
@geek , I will give it a go with that approach and I look forward in @mcdonnelldean solution.
Thanks :smile:

**Comment by mcdonnelldean** [comment]
@nicholaschantcs So unfortunately they aren't willing to share as it's commercially sensitive. This is functionality we will be looking at in a demo app in the second half of the year. It's a while away but it is on the way. Outside of that it might be an idea to ask on our gitter channel. Closing for now.
