### ISSUE TITLE
 has no method 'make$' 

### ISSUE THREAD

**Issue by AmitVirpara** [senecajs/seneca#382]
go and see the demo of this url ( http://senecajs.org/get-started/#data-storage ) it give some error.

2016-03-29T12:37:48.086Z 2qjcwukgh7lc/1459255068075/13039/- INFO	hello	Seneca/2.0.0/2qjcwukgh7lc/1459255068075/13039/-	

/var/www/html/2microservice/datasorage/product.js:3
var product = seneca.make$('product')
                     ^
TypeError: Object Seneca/2.0.0/2qjcwukgh7lc/1459255068075/13039/- has no method 'make$'
    at Object.<anonymous> (/var/www/html/2microservice/datasorage/product.js:3:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by mcdonnelldean** [comment]
@naomifeehanmoran We need to get someone to go through the examples and update them.

@AmitVirpara This is because v2.0 removed entities as a default inclusion. To fix,

1. Install the module - `npm install seneca-entity`
2. Add the plugin `seneca.use('entity')`

You need to add the use statement before using make (generally at the of the file, before your logic but after you create the seneca instance.

**Comment by naomifeehanmoran** [comment]
thanks @mcdonnelldean will get someone on this

**Comment by AmitVirpara** [comment]
thanks a lot, if possible to give me some useful example links or any kind of book or video link for learning purpose.

**Comment by naomifeehanmoran** [comment]
Hi @AmitVirpara you can find some more examples, books and videos listed here http://senecajs.org/docs/

I am currently going through the examples to update, so please be aware that you may see the same issue as above.

Also you can join the active discussion on seneca here: https://gitter.im/senecajs/seneca

and here:

https://github.com/senecajs/q-and-a/issues
