### ISSUE TITLE
Seneca data entity management function not working

### ISSUE THREAD

**Issue by ugo-buonadonna** [senecajs/seneca#383]
Trying to run this simple code:

> import seneca from 'seneca';
seneca().make$('foo'); 

Transpiled with babel:
> var _seneca = require('seneca');
var _seneca2 = _interopRequireDefault(_seneca);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`(0, _seneca2.default)().make$('foo');

Leads to this error:
`TypeError: (0 , _seneca2.default)(...).make$ is not a function`

Seems like it just can't find make function, along with other data entity functions.

The only way to make this work is:
`npm install seneca-entity --save`

and use this plugin: 
`seneca().use('seneca-entity')`

I'm using seneca version 2.0.0.

Is this a new feature? Or just a bug?

**Comment by AdrianRossouw** [comment]
Hey there @ugo-buonadonna. 

This changed in seneca 2.0, as was mentioned in the release notes : #380
we are busy updating the documentation on the website to match.

To fix this, you should also `npm install --save seneca-entity`
and before you use seneca.make you should do `seneca.use('entity')`.

related: #382

**Comment by xogeny** [comment]
I ran into this because I was trying stuff out in the documentation.  I understand it takes some time for the documentation to be changed.  But it seems like it would be nice if the `make` and `make$` functions had placeholders that generated an error that said something like "entity services are no longer loaded by default, install seneca-entity and run use('entity') to enable them".

Is there any reason to avoid that?  I'd be happy to try and create a pull request to include that functionality just to help newbies avoid this same trap.

**Comment by mcdonnelldean** [comment]
@xogeny Thats a good shout. The docs should be sorted quite soon. The issue is it would block those commands from working since it works via decoration. Having said that. The message generally needs to be clearer when a decoration is missing. I'll make a note of that.
