### ISSUE TITLE
Client timeouts are not passed to action's callback

### ISSUE THREAD

**Issue by MatthewBelkin1** [senecajs/seneca#385]
When an action that I invoke times out, the error message is only logged as a warning to the console, the error message is not passed to the callback provided when invoking the seneca action.  When you run the following example you will see a warning show up in the console, but the error is not reported to the provided callback (so the process hangs).

```javascript
'use strict';

var seneca = require('seneca'),
    senecaServer = seneca().listen({
  port: 5555
});

senecaServer.add({role: 'test', cmd: 'ping'}, function (msg, done) {
  return done(null, {ok: true});
});

var senecaClient = seneca({
  timeout: 999999999
}).client({
  port: 5555,
  pins: [
    'role:test,cmd:*'
  ],
  timeout: 1
});

senecaClient.act('role:test,cmd:ping', function (err, res) {
  console.log(err, res);
});
```

Output:
```
2016-03-31T15:57:10.222Z ksqvfsp5a2ws/1459439830212/50716/- INFO	hello	Seneca/2.0.0/ksqvfsp5a2ws/1459439830212/50716/-	
2016-03-31T15:57:10.523Z ksqvfsp5a2ws/1459439830212/50716/- INFO	listen	{port:5555}	
2016-03-31T15:57:10.534Z vgfliqj94tnn/1459439830532/50716/- INFO	hello	Seneca/2.0.0/vgfliqj94tnn/1459439830532/50716/-	
2016-03-31T15:57:10.540Z vgfliqj94tnn/1459439830532/50716/- INFO	client	{port:5555,pins:[role:test,cmd:*],timeout:1}	
2016-03-31T15:57:10.755Z vgfliqj94tnn/1459439830532/50716/- WARN	-	-	ACT	e31sdsuyclop/kopyit5c2k1g	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ACT	pjzclg29xe87/koq8hwtdmwez	hook:client,role:transport,type:web	client	invalid_origin	{port:5555,pins:[role:test,cmd:*],timeout:1,pg:cmd:*,role:test,type:web,id:pg:cmd:*,role:test,pins:role:test,cm	{kind:res,res:null,error:Error: Client request timeout,sync:true,time:{client_recv:1459439830755}}
```

**Comment by MatthewBelkin1** [comment]
I believe this is a bug.  Whenever I do not get a response from a seneca action (`role:test,cmd:ping` in the above), it forces my seneca process to timeout; what I expect to happen is the callback being called with an error after the client timeout occurs.  Should this be moved over into seneca-transport issues?

**Comment by mcdonnelldean** [comment]
Related to #398

**Comment by mcdonnelldean** [comment]
Ok I squashed this down to,

```js
'use strict'

var seneca = require('seneca')

seneca()
  .add('cmd:pingit', (msg, done) => {done(null, {ok: true})})
  .listen()

var client = seneca({timeout:200}).client({timeout: 1})

setInterval(() => {
  client.act('cmd:pingit', (err, res) => {
    console.log(err, res)
  })
}, 100)
```

The client itself gets it's own warning,

```
2016-05-13T10:22:27.578Z kny4q456ltwf/1463134945550/24356/- WARN	-	-	ACT	aoi5go70dzdk/sua6vdnpjsdm	name:transport,plugin:define,role:seneca,seq:3,tag:undefined	plugin	transport	ACT	goe2d3wr7ab5/tz0cfvg3o4qm	hook:client,role:transport,type:web	client	invalid_origin	{timeout:1,pg:,type:web,id:pg:,timeout:1,role:transport,hook:client}	{kind:res,res:null,error:Error: Client request timeout,sync:true,time:{client_recv:1463134947578}}
```

Which is emitted once per interval tick.

Next, if you set the timeout for seneca to a reasonable value, you also see the error, since this message never came back with a response. 

```js
{ [Error: seneca: Action  failed: '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined].]'
  timeout: true,
  eraro: true,
  orig: 
   { [Error: gate-executor: '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]]'
     timeout: true,
     eraro: true,
     orig: { [Error: '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]]' timeout: true },
     code: 'action-timeout',
     'gate-executor': true,
     package: 'gate-executor',
     msg: 'gate-executor: [TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]',
     details: 
      { id: '74z7f3ui75s4/5ajznqjv1bnw',
        gate: false,
        ungate: false,
        desc: undefined,
        cb: [Function: act_done],
        fn: [Function: execute_action],
        time: [Object],
        'orig$': [Object],
        'message$': '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]' },
     callpoint: 'at null._onTimeout (/Users/mcdonnelldean/repos/playground/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)' },
  code: 'act_execute',
  'gate-executor': true,
  package: 'seneca',
  msg: 'seneca: Action  failed: [TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined].',
  details: 
   { id: '74z7f3ui75s4/5ajznqjv1bnw',
     gate: false,
     ungate: false,
     desc: undefined,
     cb: [Function],
     fn: { [Function: transport_client] id: 'pg:,timeout:1' },
     time: { start: 1463135184680, end: 1463135184880 },
     'orig$': { '[Error: [TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]]' timeout: true },
     'message$': '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]',
     message: '[TIMEOUT:74z7f3ui75s4/5ajznqjv1bnw:200<1463135184880-1463135184680:undefined]',
     pattern: '',
     instance: 'Seneca/2.0.1/djrcxavjb0wy/1463135180661/24360/-',
     plugin: {} },
  callpoint: 'at null._onTimeout (/Users/mcdonnelldean/repos/playground/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)',
  seneca: true }
```

In summary,
The large timeout on the client instance is what was causing the message error to not appear. The client timeout does not trump the global timeout. This does however raise an interesting point around timeout error handling since the client timeout is sort of redundant. 

I'm going to close this as not an issue but I will be adding it to #399 Since it is related to changes in transport coming down the line.

**Comment by dgonzalez** [comment]
I know this is closed but I have a question about it that is hitting me in seneca-balance-client:

- The server (upstream) being down causes an ECONNREFUSED that gets notified as a warning and then a timeout kicks in... is this the desired behaviour when there is a clear error in the flow?

Also, the warning you mention above, I am facing the issue now that I can't act on this warning because I don't see where it happens inside of seneca-client-balance... is there a way to add code in seneca-balance-client to manipulate the warning issued and act on consequence?

To me it looks like it is in the transport plugin more than in the balance plugin but I might be wrong.

**Comment by MatthewBelkin1** [comment]
@mcdonnelldean I still think that this is an issue (but please pardon my ignorance if I am wrong).

I understand why changing the `Seneca.timeout` to a smaller number helps make the case that "everything works", but the reason I choose to use a very large timeout in my example was to show how (in this case) the error is being reported to the console after waiting for the `Seneca.client.timeout` to occur.. but it waits until the `Seneca.timeout` to report that error to the callback.

So in my example an error is reported to the console after ~1ms, but it is not reported to the callback until ~999999999ms, which makes it seem like the callback isn't getting called (because who wants to stick around for 11 days for the callback to get called). 

I guess the reason I stumbled upon this "bug" was because I didn't (still don't) fully understand the semantics behind seneca timeouts, like in this case I'm unclear what the expected behavior is when a `Seneca.client.timeout` and `Seneca.timeout` happens, so any clarity on this would be much appreciated.

**Comment by ymohammad** [comment]
@dgonzalez 
"_I am not familiar enough with Seneca_ "
I have learned more about Seneca after reading your book. 
https://www.packtpub.com/web-development/developing-microservices-nodejs

**Comment by dgonzalez** [comment]
oh thanks to you @ymohammad. I hope you found it useful. It would be amazing if we can talk a bit about what would you improve in the book. If you want, please drop me an email at nodearth@gmail.com. Thanks!

**Comment by sumitsinghp** [comment]
I'm also facing timeout issue. 
I have set the timeout to 5 minutes like this
seneca = require('seneca')({
      timeout: 300000
    });
earlier it was working fine for me but from couple of days it start failing.

["client","invalid_origin",{"pg":"","type":"web","id":"pg:","role":"transport","hook":"client","plugin$":{"name":"client$"},"fatal$":true,"meta$":{"mi":"fskwdjnzgx8f","tx":"8hlcief1efoq","id":"fskwdjnzgx8f/8hlcief1efoq","pattern":"hook:client,role:transport,type:web","action":"(v72x50itn5iu)","plugin_name":"transport","plugin_tag":"-","prior":{"chain":[],"entry":true,"depth":0},"start":1495146076193,"sync":true},"tx$":"8hlcief1efoq","port":10101,"host":"0.0.0.0","path":"/act","protocol":"http",**"timeout":5555,**"max_listen_attempts":11,"attempt_delay":222,"serverOptions":{}},{"kind":"res","res":null,"error":{"isBoom":true,"isServer":true,"output":{"statusCode":504,"payload":{"statusCode":504,"error":"Gateway Time-out","message":"Client request timeout"},"headers":{}}},"sync":true,"time":{"client_recv":1495146081757}}]

don't know why Seneca throw timeout error after 5555 miliseconds even I have set the timeout to 5 minutes. I my request is keep processing but because this it doesn't return a response.

I have tried to set the timeout with 
seneca.client({timeout: 300000}); and seneca.listen({timeout: 300000}); but it is still failing.

any help would be highly appreciated.

**Comment by markyme21** [comment]
Hi,
I've had the same issue, fixed it, but its **VERY BAD PRACTICE**.
Go to 'transport.js' at seneca-transport folder.
You will see 'timeout: 5555' 
Go ahead and change that to whatever you need.
I'm not sure why this is not getting USER defaults.
To the best of my knowledge, this is referring to client timeout. make sure you still us server timeout.

**Comment by cprpopqual** [comment]
@markyme21: You don't need to modify `seneca-transport/transport.js`. That option can be overwritten within the options passed to `Seneca()`:
```
const seneca = Seneca({
    transport: {
        'web': {
            timeout: 10000,
        },
        'tcp': {
            timeout: 10000,
        },
    },
});
```
Important notes:

* The entry for HTTP is called 'web' instead of 'http' as you might expect. This is a bit confusing, since I don't recall seeing the HTTP transport referred to as 'web' anywhere in the docs... but I may be wrong.
* You have to set the 'web' option too, even if you use 'tcp' (or something else) as your main transport. The reason is that Seneca always uses HTTP for its internal communication (`role:internals`), regardless of what's the main message transport. Setting the timeout for 'tcp' but not setting it for 'web' will result in the obscure 'invalid_origin' errors listed above.
