### ISSUE TITLE
Incorrect pattern matched, when pattern is specified explictly

### ISSUE THREAD

**Issue by mirceaalexandru** [senecajs/seneca#415]
I have the case when pattern is specified explicitly. In this case it seems that pattern JSON and payload are merged and then the pattern matching is applied, which seems to be incorrect. If pattern is specified explicitly then this should be the only information used for matching, regardless the data in the payload JSON object.

Take a look on the following code:

```javascript
var seneca = require('seneca')()

seneca.add('role: x, a: 1', function(args, done){
  console.log('Called a:1')
  done()
})

seneca.add('role: x, b: 1', function (args, done){
  console.log('Called b:1')
  done()
})


seneca.act('role: x, b: 1', {a: 1, c: 1}, function(){
  console.log('done')
})
```

result will be:

```
2016-05-05T11:26:21.653Z 93jo4sli8a9b/1462447581642/13447/- INFO        hello   Seneca/2.0.1/93jo4sli8a9b/1462447581642/13447/-
Called a:1
done
```

**Comment by mcdonnelldean** [comment]
I feel like we should have a flag for this. I agree basically, because it makes the model easier to follow, but a blanket change would break the world. Let me first check if we have such a flag, if not I don't think it's a big job to add in 4.0 or 5.0

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Changed this to a feature request. It's something I want to discuss with a few people but provisionally I think this is a good thing to put in.

**Comment by rjrodger** [comment]
Sorry guys this is by design :)
The multiple arguments are just a convenience - pattern matching is applied on a message basis - ie on the full JSON document as received.
Probably needs to be a FAQ.

**Comment by mcdonnelldean** [comment]
@rjrodger No doubt and I can see the reason for it being the way it is, especially when working with Entities or something. But given the difference is a simple merge operation could we not have this as a feature behind a flag?

The premise would be,

- flag off, message and payload are unique, message is matched only
- flag on, message and payload are merged, merged object is the message.

Default would be as is, flag off, since this option could trip people up.

The reasoning behind this request is it allows you to do this,

```js
seneca.add('role:catch,cmd:it, filter:foo', (msg, done) => { })
            .add('role:catch,cmd:it, filter:bar', (msg, done) => { })

seneca.act('role:catch,cmd:it', payload)
```

Which leads to much terser and easier to understand code. Patterns are easily identifiable because there is less construction needed.

**Comment by mcdonnelldean** [comment]
Yeah ignore my last comment, I basically argued in favour of not doing this :D

@mirceaalexandru I know there was an actual use case for why this was raised in Nodezoo. Can you remember what it was. I would like to tease it out here. 

The fact is if we thought this was the way to go, working through that problem and updating the FAQ is probably a good idea. I can update the FAQ but I want to use the real problem we had.

**Comment by mirceaalexandru** [comment]
@mcdonnelldean 
I don't remember exactly the place, I will take a look, but the scenario was simple. We do have there patterns with something like:

`role: 'info', cmd: 'get'`
and
`role:'info', req:'part'`

and I wanted to use one of them and matched the other one.

So basically, my concern is that if we do not have a uniform pattern used in the whole application (like using only `role/cmd` for defining patterns) we might have situations when the action being called to be other than the expected one because the payload object contains at one moment a key that will match another pattern. In this case we will not have a predictable flow inside the application, it will depend on the payload object content (which might be desired behavior or not !).

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Ah yes! now I remember, we were having pattern collisions as the system became more complex due to our payload key names.

I had a think about this one actually and never wrote it down.

My feeling here is that the real issue is the some of patterns in nodezoo are bad because the are easily matched by common keys used in payloads.

One of the things on my list is to better arrange the patterns in Nodezoo and name them appropriately. Community feedback suggests that `req:part / res:part` stuff is confusing and could be named better.

**Comment by mirceaalexandru** [comment]
@mcdonnelldean Agree with you. 

On the other hand specifying explicitly the pattern might help exactly in such cases, when we can have these collisions and we want to make sure that the action being called is exactly the desired one.

**Comment by rjrodger** [comment]
This issue arises when patterns have the same number of properties. Which pattern "wins"?

  * a:1, b:1
  * a:1, c:1

There is a rule to cover this: alphabetical precedence. So a:1, b:1 wins, as b is earlier than c
See: https://github.com/rjrodger/patrun#the-rules

The pattern set must be *fully-ordered*, otherwise the engine can't decide where to send messages.

**Comment by mirceaalexandru** [comment]
@rjrodger Yes, I agree with you.

The issue is more about the fact that the pattern is supplied separately and I was under impression that because of this it will be used just that for pattern matching. I think we should have this specified in documentation.

I will close this issue.
