### ISSUE TITLE
Seneca DB connectivity

### ISSUE THREAD

**Issue by nrusingha-bestray** [senecajs/seneca#428]
Hi,
I am new to seneca. from last few days I am trying to insert some data into mongo db but I was a little but confused.
Can you please give a step by step guide to do this.
I am currently using Windows 7, Node 4.4, Seneca latest.
Thanks

**Comment by mirceaalexandru** [comment]
Hi @nrusingha-bestray ,

this documentation should help you:
http://senecajs.org/tutorials/understanding-data-entities.html

If you want to use mongo then you should use this store:
https://github.com/senecajs/seneca-mongo-store

and because you are using the latest seneca version you should use also seneca-entity (https://github.com/senecajs/seneca-entity)

So your code will look like this:

```javascript
var Entity = require('seneca-entity')
var MongoStore = require('mongo-store')

var seneca = require('seneca')()
seneca.use(Entity)
seneca.use(MongoStore, {
  uri: 'mongodb://120.0.0.1:27017/dbname'
})

seneca.ready(function () {
  var apple = seneca.make$('fruit')
  apple.name  = 'Pink Lady'
  apple.price = 0.99
  apple.save$(function (err,apple) {
    console.log( "apple.id = "+apple.id  )
  })
})
```

**Comment by nrusingha-bestray** [comment]
Hi. mirceaalexandru
Thanks for your reply.
Your quotes are quite helpful.Now data are saving in mongodb
Next can you give some basic idea that It will fetch parameters given from view (e.g. from  ejs pages in sails) --> manipulate it in middle layer --> then saves in db and returns a response to view.

Thanks again

**Comment by mirceaalexandru** [comment]
I hope I understood your question. 

You need to execute the seneca actions from your controllers, so all seneca actions will be used as services that runs between your controller and the model. 

The seneca actions can then process request, read/write into DB using its store and generate the response for controller.

For Express & Hapi, Seneca has a build in plugin that can be used to register your web service API endpoints (https://github.com/senecajs/seneca-web). Please note that seneca-web is loaded by default by seneca but in the near future it might not be the case and you might need to load it explicitly.

**Comment by nrusingha-bestray** [comment]
Hi ,
as you said I created one controller and from here I call the service layer.
Here is my code:

SavedataController:
----------------------------
saveData: function(req,res){
    var SenecaService=require("../services/SenecaService");
    var say=req.param('say');
    var name=req.param('name');
    SenecaService.saveDetails(say, name, function(err, data){
      console.log('--- Data: '+data);
    })
  }


SenecaService:
---------------------------
var seneca=require('seneca')()
seneca.use('entity')
seneca.use('mongo-store',{
  name:'senecatestdb',
  host:'localhost',
  port:27017
})
var table1 = seneca.make$('senecatesttable')
module.exports = {
  saveDetails: function(say, name, callback){
    table1.name  = say
    table1.price = name
    table1.save$(function(err,data){
      if( err ){
        return console.log(err);
      } else{
        console.log( "--------------->Data Saved [ from Service() ]: "+data)
        callback(null, data);
      }
    })
  }
}

Now my question is Am I going in right direction?
Because here I am not doing any pattern match. Just saving the data which came from controller.

Thanks for your help.

**Comment by mirceaalexandru** [comment]
No, is not really OK how you did it, here are some examples, maybe it will help you:
https://github.com/rjrodger/seneca-examples
https://github.com/nodezoo/nodezoo-web

**Comment by mcdonnelldean** [comment]
@nrusingha-bestray nodezoo-web is a good example of what you are looking for. We use Hapi for most of our examples because it has an addin called Chairo that decorates Hapi with Seneca. This means I can do things like `request.seneca.act`. See nodezoo-web's [api routes](https://github.com/nodezoo/nodezoo-web/blob/master/server/routes/api.js).

In seneca your logic always lives in a plugin that is loaded into seneca. In nodezoo-web we go a step further, we set up a link (.client) to an second microservice (nodezoo-info) and defer all the work to it.

The problem above with your code is you are not using Seneca for anything more that storage. In this case it would be simpler for you to just use a db connector module instead, or something like backbone.

Seneca's primary use case is to build message based microservices. In the context of your app. Your controllers would simply send off a number of `seneca.act()` and return the  result.

### In your controller service
Somewhere global you need something like

```js
var seneca = require('seneca')()

seneca.client({port:6400, pin: 'role:service,cmd:*'})
```

And in your controller,

```js
saveData: function(req,res) {
  var payload = {
    name: req.param('name'),
    price: req.param('price')
  }

  // up to you where this comes from, nodezoo-web uses hapi to get in on request.
  seneca.act('role:service,cmd:save', {data: payload}, (err, reply) => {
    console.log(err, data)
  })  
}
```

### In another microservice
Now lets put all of your logic into it's own microservice that can run stand alone.

```js
var opts = {
  mongo: {
    name: 'senecatestdb', 
    host: 'localhost', 
    port: 27017
  }
}

require('seneca')()
  .use('entity')
  .use('mongo-store', opts.mongo)
  .use(logic)
  .listen(6400)

function logic (options) {
  var seneca = this

  seneca.add('role:service,cmd:save', (data, done) => {
    var entity = seneca.make$('some_entity')
    
    entity.name = data.name
    entity.price = data.price
    
    entity.save$((err, data) =>{
      if (err) done(null, {ok: false, err: err})
       else done(null, {ok:true, data: data.data$()}) // data$ strips out store stuff
    })
}
```

In the code above it is assumed that your controller and the logic live in two different apps. The second example above is a self contained little microservice that you could make into it's own module. Notice that the logic is all in `logic`.

If you didn't want your logic in a different microserice you merge both together, so,

### All in one service
Somewhere global you need something like

```js
var opts = {
  mongo: {
    name: 'senecatestdb', 
    host: 'localhost', 
    port: 27017
  }
}

var seneca = require('seneca')()
  .use('entity')
  .use('mongo-store', opts.mongo)
  .use(logic)

function logic (options) {
  var seneca = this

  seneca.add('role:service,cmd:save', (data, done) => {
    var entity = seneca.make$('some_entity')
    
    entity.name = data.name
    entity.price = data.price
    
    entity.save$((err, data) =>{
      if (err) done(null, {ok: false, err: err})
       else done(null, {ok:true, data: data.data$()}) // data$ strips out store stuff
    })
}

```

And in your controller it stays the same,

```js
saveData: function(req,res) {
  var payload = {
    name: req.param('name'),
    price: req.param('price')
  }

  // up to you where this comes from, nodezoo-web uses hapi to get in on request.
  seneca.act('role:service,cmd:save', {data: payload}, (err, reply) => {
    console.log(err, data)
  })  
}
```

**Comment by nrusingha-bestray** [comment]
Hi mcdonnelldean,
sorry I am late and thanks for your demonstration.
I was working on that.
Please tell me how to integrate Hapi in Node 0.10
[ Note: I am using Node 0.10 
If I switch to Node 4.4 or like that some other functionalities like 'bcrypt' will not work in my project ]
Thanks

**Comment by mcdonnelldean** [comment]
@nrusingha-bestray I have never used Hapi with 0.10 so I can't help here.

One thing I would note is that 0.10 is going end of life before the end of they year, at that point Seneca will no longer actively support 0.10 (although it may still 'work'). My suggestion is to find an alternative to BCrypt since you are going to find support for modules very VERY hard.

I'm going to go ahead and close this as answered. If you have any more questions feel free to reopen or to make new issues.
