### ISSUE TITLE
client / listen with no pin does not work

### ISSUE THREAD

**Issue by jeromevalentin** [senecajs/seneca#518]
I'm developing an application sharing the seneca-user library with the seneca client / listen mechanism.
I'm using the version below:

```
    "seneca": "^3.0.0",
    "seneca-basic": "^0.5.0",
    "seneca-entity": "^1.3.0",
    "seneca-mongo-store": "^1.1.0",
    "seneca-user": "^2.1.0"
```

See the example code below:

SERVER :
---
```js
import Seneca from 'seneca';

let seneca = Seneca();
seneca.use('entity');
seneca.use("basic");
seneca.use("user");
seneca.ready((err) => {
  if (err) throw new Error(err);
  console.log("SERVER: USER DELETE?"+seneca.has({role:"user", cmd:"delete"}));
  console.log("SERVER: USER REMOVE?"+seneca.has({role:"user", cmd:"remove"}));
  seneca.listen({
    type: 'http',
    host: '127.0.0.1',
    port: '4051'
  });
});
```
CLIENT:
---
```js
import Seneca from "seneca";

let seneca = Seneca();

seneca.client({
    type: 'http',
    host: '127.0.0.1',
    port: '4051'
    // ,    pin: {role: 'user', cmd:'*'}
});
seneca.use("entity");
seneca.ready(function (err) {
   if (err) {
     console.log("NOT READY: "+err);
     return;
   }
   console.log(">>>>> READY");
   console.log("CLIENT: USER DELETE?"+seneca.has({role:"user", cmd:"delete"}));
   console.log("CLIENT: USER REMOVE?"+seneca.has({role:"user", cmd:"remove"}));
});
```
Running server and client produce following logs:
Server: 
--
```
{"kind":"notice","notice":"hello","level":"info","seneca":"is02oxippea3/1472650404544/21284/3.0.0/-","when":1472650404563}
SERVER: USER DELETE?true
SERVER: USER REMOVE?true
```

Client:
--
```
{"kind":"notice","notice":"hello","level":"info","seneca":"nfj946pie6ck/1472647364612/19511/3.0.0/-","when":1472647364630}
>>>>> READY
CLIENT: USER DELETE?true
CLIENT: USER REMOVE?false
```

As you can notice the "role:user, cmd:remove" pattern is not accessible from client while "role:user,cmd:delete" is!

NOTE: uncommenting the pin line in the client call is a workaround ... 

By the way, this is highlighting an issue.

Hope it helps,
Regards,
Jérôme

**Comment by mihaidma** [comment]
related to this https://github.com/senecajs/seneca-transport/issues/117

**Comment by jeromevalentin** [comment]
ok thanks for the link, but the problem is still present on 3.0.0, so I'm not sure it is exactly the same.

**Comment by mcdonnelldean** [comment]
Hey @jeromevalentin I updated your post just for readability. 

Yeah so looking over the code this is definitely related. There is no explicit fix made for this yet which is why I suspect it still happens in 3.0.

Generally I would recommend always using pins. It is good practice as it makes the API more readable and reduces collisions when your system grows to a particular size. 

Having said that. This still is a bug, catchall on client and servers should work as expected using your code above. 

I'm going to merge this with https://github.com/senecajs/seneca-transport/issues/117 so it doesn't get lost. Feel free to comment there if you have anymore questions.

__merged with https://github.com/senecajs/seneca-transport/issues/117__
