### ISSUE TITLE
Significantly increased memory consumption since 3.0.0 update

### ISSUE THREAD

**Issue by jluchiji** [senecajs/seneca#549]
I am noticing significantly increased memory consumption since the `3.0.0` update. I ran the following script on both `2.1.0` and `3.1.0` versions: 

```sh
var _ = require('lodash');
var seneca = require('seneca')({
  actcache: { active: false }
});


var payload = require('./payload'); // a 70kb json file

seneca.add('cmd:test', function(msg, done) {
  done(null, _.clone(payload));
});


var counter = 0;
setInterval(function() {
  if (counter >= 20000) {
    console.log(process.memoryUsage());
    process.exit(0);
  }

  seneca.act('cmd:test', function(err, res) {
    console.log(counter++);
  });
}, 5);
```

And i got the following results:
```
2.1.0: { rss: 110706688, heapTotal: 82733152, heapUsed: 43702008 }
3.1.0: { rss: 224366592, heapTotal: 196295264, heapUsed: 165344232 }
```

**EDIT**: I did a few heap profiles of the code above, and did a comparison. I seems that a lot of memory is taken up by closures. More specifically, the `log_level()`, `act_delegate_log_modifier()`, `log_modifier()` and others. I would gladly provide my heap snapshots if such a need arises.

**Comment by Yumonra07** [comment]
I have a similiar problem with one of my services. Memory usage keeps increasing with no upper limit. I ran the code you published in this issue with the Seneca 3.1.0(NPM) and also with the Seneca's master branch. Memory Usage issue seems to be lighter in the current master branch. I made sure of this by outputting the memory usage information and a timestamp in csv format and making a graph out of those files in plot.ly.

I then started to investigate the Seneca code to see if i could find where the problem was and i think i've found it. The problem seems to be [Line 921 in seneca.js](https://github.com/senecajs/seneca/blob/master/seneca.js#L921), the gate executor makes the app somehow leak memory. I'm not sure how the memory leak started only after i've upgraded to seneca 3, it seems the gate-executor is last updated 2 months ago.

I will be investigating the changes between 3.1.0 and current branch. I will also try to understand how gate-executor causes this issue. My current guess is that the function you store in gate-executor to call when a timeout occurs, doesn't get released, but i haven't take a look at the code atm.

I uploaded 2 csv files to gist; one showing the memory usage after changing the Line 921 in seneca.js, and other showing the memory usage with the current branch. I also put the code i've used to generate this csv files and a diff showing how i edited seneca.js. You can [check the gist here](https://gist.github.com/Yumonra07/6faa8aa49c23d58cc6a07cdb5585fcd9).

**Comment by mcdonnelldean** [comment]
Possibly related to #517 @rjrodger you may need to investigate here.

**Comment by rjrodger** [comment]
@jluchiji @Yumonra07 Thank you so much! Your investigation really helped isolate the issue. An array in gate-executor was not being cleared and just kept growing. Ironic as the manual timeout checking is to avoid resource consumption from lots of setTimeouts.
