### ISSUE TITLE
Memory Leak in History (and Active Flag does not to be working)

### ISSUE THREAD

**Issue by marcushill** [senecajs/seneca#680]
My team has noticed a significant memory leak in version: `seneca@3.4.3`. We have a rather long running seneca action in which we make a large number (on the order of a few hundred thousand) calls to other seneca actions. Memory utilization would spike as expected, but the corresponding drop off after those results should have been freed from memory did not occur. 

We took a number of heap dumps and it became clear that the Seneca History object contained the message (and response?) of every Seneca action we called. I believe this behavior is intended, but it doesn't ever clean up after itself over the course of the couple of hours that the job runs. I believe that [this](https://github.com/senecajs/seneca/blob/fa2c56b8afca417f9874dea8ca81d12f4cd00ad2/lib/common.js#L580) function has a bug in it that is causing `prune` not to delete messages as often as it should. 

Also, setting history.active to false in the config does not fully disable history functionality: 
```js
{
   history: {
     active: false
   }
}
```

**Comment by AboutBrace** [comment]
I noticed the same issue with the history feature in Seneca when I snapped some memory heaps roughly a month ago. I didn't have the time to go hunt it down precisely though. Glad I wasn't the only one to notice this.

**Comment by marcushill** [comment]
I'm glad someone put the time into actually it. We solved our initial error and then priority shifted to other work. 

For anyone who finds this before it is fixed:

The history holds to a full copy of every message until the message would have timed out, even after it has received a response. We were able to fix this problem for ourselves by shortening the timeout on requests made from our long running Seneca action.

**Comment by rjrodger** [comment]
Great catch! Thank you - fixed history disable

**Comment by suyuan1203** [comment]
@jeromevalentin "parent_meta_trace memory leak" could be a problem of Seneca plugin "this"

```
module.exports = function demo_plugin() {
  this.add('role: service1, cmd: get_name',  (msg, reply) => {
    this.act('role: service2, cmd: get_name', { name: msg.name }, function (err, result) {
      if (err) return reply(err);
      reply(null, {
        name: result.name
      });
    });
  });
}
```
Be careful, the second "this" is a reference of demo_plugin instance, instead of a new Seneca instance

Seneca creates a new Seneca instance for each action request. And it will be released after the request is finished. But a Seneca plugin will stay alive as soon as the service is alive.

```
function outward_trace(ctxt, data) {
  var private$ = ctxt.seneca.private$

  var meta = data.meta
  var reply_meta = data.reply_meta

  if (meta && reply_meta) {
    meta.trace = meta.trace || []
    meta.trace.push({
      desc: Common.make_trace_desc(reply_meta),
      trace: reply_meta.trace || []
    })
  }

  var parent_meta = private$.act && private$.act.parent
  if (parent_meta) {
    parent_meta.trace = parent_meta.trace || []
    parent_meta.trace.push({
      desc: Common.make_trace_desc(meta),
      trace: meta.trace || []
    })
  }
}
```
Here the parent of the inner action is always the plugin instance, so the "trace" array of the plugin will increase infinitely

It is by design that Seneca plugin is also a Seneca instance. And it just works even I reference the wrong "this". 

@rjrodger Is there a way we can prevent bugs like this? Like a plugin's act method can only be called inside certain context?

**Comment by suyuan1203** [comment]
Since every act has a uniq id, it seems useless to keep a history of act object.

```
function inward_act_cache(ctxt, data) {
  var so = ctxt.options
  var meta = data.meta

  var actid = meta.id
  var private$ = ctxt.seneca.private$

  if (actid != null && so.history.active) {
    var actdetails = private$.history.get(actid)
    if (actdetails) {
    }
  }
}
```
if (actdetails) could always be false.

**Comment by tswaters** [comment]
We had a massive memory leak in prod - resulting in OOMKILL every day or so for certain services, far more frequent deaths when the system was under load.... tracked it down to plugins that used arrow functions instead of `function` and called `act` on the plugin's instance.  This should _definitely_ be in a readme somewhere.
