### ISSUE TITLE
Error handling issue in seneca@3.4.3

### ISSUE THREAD

**Issue by davide-talesco** [senecajs/seneca#685]
All,

let me say first seneca is awesome! :)
Back to the issue, can you please clarify why pattern 'cmd:test2' crashes Seneca whilst pattern 'cmd:test3' doesn't?

I noticed seneca instance @placeholder1 is different than seneca instance @placeholder2 ?
Is this the expected behaviour?
am I missing something?
Aren't those expected to be the same object instance?

```
var Promise = require('bluebird');
var seneca = require('seneca')();

seneca
  .test('print')

  .use(otherTests)

  .client({pin:'cmd:whatever', port:9040})

  .use('seneca-repl', {port:10030})

  .listen(9030);

function otherTests(options){
// this seneca instance has fixedargs.fatal$=true - @placeholder1
  const seneca = this;
  const act = Promise.promisify(seneca.act, {context: seneca});

  seneca.add( 'cmd:test2', test2 );
  seneca.add( 'cmd:test3', test3 );

  function test2( msg, reply ) {
    act('cmd:whatever', msg)
      .then(reply)
      .catch(reply)
  }

  function test3( msg, reply ) {
// this seneca instance has fixedargs.fatal$=false WHY??? - @placeholder2
    const seneca = this;
    const act = Promise.promisify(seneca.act, {context: seneca});
    act('cmd:whatever', msg)
      .then(reply)
      .catch(reply)
  }
}
```
Thanks,
Davide

**Comment by davide-talesco** [comment]
seems kind of connected to #439

**Comment by davide-talesco** [comment]
I noticed that if I add at the root scope
```
seneca.actPromise = Promise.promisify(seneca.act, {context: seneca});
```
and replace all act calls to be this.actPromise it works as expeceted...

but is this a safe way to promisify act ?

**Comment by ryanfields** [comment]
We chatted about this on gitter, but for anyone else who comes by here I wanted to explain what's happening here.  Seneca plugins are required to install successfully.  Any error of any kind during a plugin setup may leave Seneca in an unknown state.  Because of this requirement, Seneca treats any error that arises during plugin installation as fatal.

As for whether or not it's safe to acquire a Seneca reference in an outer scope and use it from an inner scope, yes.  Every one of my services operates this way and I'm pretty sure it is the preferred way of referencing Seneca.
